### ISSUE TITLE
jblas on multiple jvm instances

### ISSUE THREAD

**Issue by vimpagliazzo** [mikiobraun/jblas#41]
Given that there is already a jvm process running jblas, if a second jvm process is run (windows 64bit in my tests), I get the error
-- org.jblas ERROR Couldn't load copied link file: java.lang.UnsatisfiedLinkError: C:\Windows\Temp\libgcc_s_dw2-1.dll: The process cannot access the file because it is being used by another process.

-- org.jblas ERROR Couldn't load copied link file: java.lang.UnsatisfiedLinkError: C:\Windows\Temp\jblas2376714726013803026jblas_arch_flavor.dll: Can't find dependent libraries.

**Comment by mikiobraun** [comment]
Alright, new release out. This should be fixed now!
