### ISSUE TITLE
broken equals / hashCode contract

### ISSUE THREAD

**Issue by m0nzderr** [mikiobraun/jblas#43]
Hi, 
this is realy great lib. I like it so much, especially for almost-"matlab" comfort. But there is one annoying thing: bad implementation of .equals(). 
Thing is, that current equals() has several potential problems:
   a) a comparison with a hard-coded tolerance (hey, what if 1e-6 is the NOT a precision I seek?)
   b) NaNs are just ignored ( [1 2 3] equals [1 NaN 3]) 
   c) equal matrices according to such implementation, will have different hashCodes - and this is a realy bad news for those who is going to use jblas objects in complex systems with caching, hashmaps. Things may go really bad for them. 

AFIK, from A.equals(B) in Java we expect A.hashCode()==B.hashCode(), while opposite is not necessarily true.

Since jblas does not provide interfaces or abstract classes (for performance reasons, I guess) there is no elegant way to fix .equals() by simple overriding. So, my proposal is the following:

1) refactor current implementation of equals(Object o) into e.g.
compare(SomeMatrix other, double tol)

2) implement equals(Object o) based on exact value (=byte level) comparison (e.g, using Arrays.equals(this.data,other.data).

Thanks!

**Comment by mikiobraun** [comment]
Ok, I fixed this as suggested. There's a new function compare now (with tolerance), and equals uses Arrays.equals on the byte arrays.
