### ISSUE TITLE
DoubleMatrix.mul(DoubleMatrix) documentation incorrect.

### ISSUE THREAD

**Issue by GratefulTony** [mikiobraun/jblas#45]
Doc. says mul is in place, it actually creates a new object.

http://mikiobraun.github.io/jblas/javadoc/org/jblas/DoubleMatrix.html
  DoubleMatrix 	mul(DoubleMatrix other)
          Elementwise multiply by a matrix (in place).

**Comment by mikiobraun** [comment]
Fixed
