### ISSUE TITLE
internal representation of DoubleMatrix fundamentally contradict with documentation

### ISSUE THREAD

**Issue by boscogh** [mikiobraun/jblas#63]
from the documentation I expected that internally DoubleMatrix represented as single array of row after row, i.e. row0:column0, column2..column5; row1..., row2... etc

follow this logic, if I need to took DoubleMatrix[row1][column4], it would be length of 1 row + 4, i.e.
"rowIndex  *  columns + columnIndex"
"1 * 5+ 4"

but after week of fighting, I decided to look into code of DoubleMatrix.index method.
    /** Get index of an element */
    public int index(int rowIndex, int columnIndex) {
        return rowIndex + rows * columnIndex;
    }

it is completely opposite! so the internal representation of DoubleMatrix is NOT row after row.
it is column, after column, because of this index method.

I am really surprised to find such fundamental difference. it took me more that 3 days of debug and test to understand that it was not my fault, because of my belief in documentation.

**Comment by mikiobraun** [comment]
Hi Boscogh,

sorry for the confusion. The memory layout is dictated by the use of the LAPACK and BLAS libraries which prefer this kind of layout called column major layout.

In order to fix this, can you point out where the documentation is misleading or false?

-M

**Comment by boscogh** [comment]
thanks for comment. yesterday I was so surprised that even started to doubt in DoubleMatrix.mmul operation, but of course it works. I'm sorry for some dramatization earlier.
the documentation I mentioned is 
http://jblas.org/javadoc/org/jblas/DoubleMatrix.html#data
there are also some sort of same statement in constructors 
http://jblas.org/javadoc/org/jblas/DoubleMatrix.html#DoubleMatrix(int, int, double...)
http://jblas.org/javadoc/org/jblas/DoubleMatrix.html#DoubleMatrix(double[][])
and have a look into issue #60 - it is about another contructor
http://jblas.org/javadoc/org/jblas/DoubleMatrix.html#DoubleMatrix(int)
I understand you did the trick of transposing matrix in each contructor from double[][] to column ordered matrix, but this could be done by calling code, since it is anyway did some job on preparing data. in this case filling the 2D data-matrix would be much easier, and less time consuming, it would be just a set of System.arrayCopy operations. 

That I was trying to achieve is to traverse DoubleMatrix in incremental order, i.e. DoubleMatrix.data[index++], and execute several computations at once, saving some time on addressing the memory. I read somewhere, that CPU will much faster operates with array if sequential access is used, rather then some complex indexing, because CPU alway load a buch of data to the cache, so next time it access a nearby element of the array it is right there in the cache.

all this transpositions seems a bit more complex for me as they are not always easily predicted.
for instance the code
		DoubleMatrix d = new DoubleMatrix(new double[][]{{1d, 2d, 3d}, {4d, 5d, 6d}, {7d, 8d, 9d}, {10, 11, 12}});
		d.print();
		DoubleMatrix e = new DoubleMatrix(d.data);
		e.reshape(d.columns, d.rows);
		e.print();

produced
[1,000000, 2,000000, 3,000000; 
4,000000, 5,000000, 6,000000; 
7,000000, 8,000000, 9,000000; 
10,000000, 11,000000, 12,000000]

[1,000000, 10,000000, 8,000000, 6,000000; 
4,000000, 2,000000, 11,000000, 9,000000; 
7,000000, 5,000000, 3,000000, 12,000000]

and it is not easy to understand why.

**Comment by mikiobraun** [comment]
Oh yeah, it almost looks like I consistently mixed up row and column... that's very bad.

I will need to fix that!

-M

**Comment by boscogh** [comment]
mikiobraun, hopefully you will have some time to deal with documentation in future.
you know, I was trying to compare a performance of you lib, expecially in gemv
vs pure java and with JNI+MKL and JNA+MKL
your library beat them all! great job! thank you for your work. I just realized you started almost 7 years ago, so it shouldn't now takes too much of your attention.

my "test" program internally performs a lot of gemv calculations (I think >150000), for 1 single run with 
jblas it takes 9.769 seconds to complete, 
JNI + MKL (CBLAS) takes 10.552 seconds
JNA + MKL (CBLAS) it is 11.211 seconds
pure Java (linear incremental indexing) it takes 12.585 seconds
- this is the lowest time from several runs.

**Comment by mikiobraun** [comment]
Should be fixed now.
